DELIMITER $$

DROP procedure IF EXISTS `setUserActiveByGUID`;

CREATE DEFINER=`root`@`localhost` PROCEDURE `setUserActiveByGUID`(
	IN target_guid VARCHAR(255)
) 
BEGIN

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
		-- ERROR
		ROLLBACK;
    END;

	DECLARE EXIT HANDLER FOR SQLWARNING
	BEGIN
		-- WARNING
		ROLLBACK;
	END;

    START TRANSACTION;
    UPDATE user u1
		SET u1.active = TRUE
	WHERE u1.guid = target_guid;
    COMMIT;
END$$

DELIMITER ;
